services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend-express-app
        develop:
            watch:
                - action: rebuild
                  path: ./package.json
                - action: rebuild
                  path: ./src
                  target: /app
                  ignore:
                      - node_modules/
                      - .vscode/
                      - .git/
                      - .env
                      - tsconfig.tsbuildinfo
        env_file: '.env'
        restart: unless-stopped
        ports:
            - '${PORT:-3000}:3000'
        environment:
            - JWT_SECRET="dooooooood"
        depends_on:
            - mongo
        networks:
            - 2fa_network
        # command: pnpm start:docker
        # volumes:
        # - backend_data_2fa:/app

    mongo:
        image: mongo
        container_name: mongo
        env_file: '.env'
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        restart: always
        ports:
            - '27017:${MONGO_PORT:-27017}'
        volumes:
            - mongo_data_2fa_v1:/data/db
        networks:
            - 2fa_network

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        env_file: '.env'
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ports:
            - '${MONGO_EXPRESS_PORT:-8081}:8081'
        depends_on:
            - mongo
        networks:
            - 2fa_network

volumes:
    # backend_data_2fa:
    mongo_data_2fa_v1:

networks:
    2fa_network:
        driver: bridge
