version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://root:example@mongo:27017
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    container_name: mongo_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express_container
    restart: always
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - '8081:8081'

volumes:
  mongo_data:
